# Generated by Django 3.2.19 on 2024-12-15 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200)),
                ('tasks_name', models.CharField(max_length=150)),
                ('tasks_decs', models.TextField()),
                ('tasks_detail', models.TextField()),
                ('tasks_start_date', models.DateField()),
                ('tasks_end_date', models.DateField()),
                ('tasks_start_time', models.TimeField()),
                ('tasks_end_time', models.TimeField()),
                ('tasks_continued', models.CharField(max_length=50)),
                ('is_task_repeat', models.BooleanField(default=False)),
                ('tasks_status', models.IntegerField(default=1)),
                ('tasks_time_node', models.DateTimeField(blank=True, null=True)),
                ('left_time', models.IntegerField(default=0)),
                ('task_location', models.CharField(max_length=150)),
                ('task_deliver_content', models.CharField(max_length=150)),
                ('task_deliver_object', models.CharField(max_length=150)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
